system("apt-get update", intern = TRUE)
system("apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev", intern = TRUE)

install.packages("tidyverse")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("readr")
install.packages("lubridate")
install.packages("corrplot")
install.packages("randomForest")
install.packages("xgboost")
install.packages("caret")
install.packages("ranger")
install.packages("car")

library(tidyverse)
library(ggplot2)
library(dplyr)
library(readr)
library(lubridate)
library(corrplot)
library(randomForest)
library(xgboost)
library(caret)
library(ranger)
library("car")
